trigger:
- main

pool:
  name: Default

steps:
- checkout: self

- script: |
    echo "ROOT FILES:"
    dir
  displayName: 'Check root'

- script: |
    echo "CHECK ALL FOLDERS:"
    dir /s
  displayName: 'Check full structure'

- script: |
    npm install
  displayName: 'Install (temporary)'