trigger:
- main

pool:
  name: Default

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: npm install
  workingDirectory: app
  displayName: 'Install dependencies'

- script: echo "Build successful"
  displayName: 'Build Step'